### ISSUE TITLE
AC: Wild World music?

### ISSUE THREAD

**Issue by elleirGab** [mn6/nook-desktop#12]
is it just me or is there no music from wild world?

(unrelated, but i made a french translation in one of the forks! i'm not good at github, so good luck on importing it or whatever xP)

**Comment by mn6** [comment]
As far as I know, the City Folk music is the same as the Wild World music, but the quality is enhanced. If this isn't right, we could add the Wild World music, but from my listening that's what seems to be the case.

**Comment by elleirGab** [comment]
oh wait, you're right. i thought the instruments sounded different, but you're right, it's exactly the same. woopsies! in that case, my grain of salt is that it may be less confusing to change the name to Wild World + City Folk or Wild World/City Folk or something like that, 'cause my dumbass thought it was missing.

thank you very much for your work on this free project! good luck!
