### ISSUE TITLE
 AC: Wild World/City Folk (DS) - 11PM STILL has an incorrect loop.

### ISSUE THREAD

**Issue by Splat-A-Tat** [mn6/nook-desktop#13]
Continuation of an issue started [here.](https://github.com/mn6/nook/issues/39)

The 11PM theme is missing an accordion section that plays after two loops of the main part of the song. 
For reference, [this is the accordion part I'm talking about.](https://youtu.be/1p49QEWaezs?t=45)

It seems that while the issue was marked as fixed and closed, this section is still missing from both the desktop app and the soon to be deprecated Chrome extension version (as well as the Firefox version, but that version has just not been updated for two years anyway).

Again, this issue is present in the Normal and Rainy variations of the song, but not the Snow variation.

**Comment by mn6** [comment]
Nice catch! Was able to fix it, including the accordion bit this time. Should automatically download the new version next time you listen to it with Nook.
