### ISSUE TITLE
French translation (by elleirGab)

### ISSUE THREAD

**Issue by elleirGab** [mn6/nook-desktop#14]
I made a french translation about a week ago but I suck at GitHub so it's hidden in a fork. Here's the [raw code](https://raw.githubusercontent.com/elleirGab/nook-desktop/patch-1/app/main/i18n/Nook_French.json) for ya!

{
    "AC: Population Growing (GC)": "AC: Population Growing (GC)",
    "AC: City Folk (Wii)": "AC: City Folk (Wii)",
    "AC: City Folk (Wii) [Rainy]": "AC: City Folk (Wii) [Pluie]",
    "AC: City Folk (Wii) [Snowy]": "AC: City Folk (Wii) [Neige]",
    "AC: New Leaf (3DS)": "AC: New Leaf (3DS)",
    "AC: New Leaf (3DS) [Rainy]": "AC: New Leaf (3DS) [Pluie]",
    "AC: New Leaf (3DS) [Snowy]": "AC: New Leaf (3DS) [Neige]",
    "AC: New Horizons (Switch)": "AC: New Horizons (Switch)",
    "K.K. Slider": "Kéké Laglisse",
    "Random": "Aléatoire",
    "Music Volume": "Volume de la musique",
    "Rain Volume": "Volume de la pluie",
    "Settings": "Paramètres",
    "Home": "Accueil",
    "Minimize to tray": "Réduire à la barre de tâches",
    "Exit Nook": "Fermer Nook",
    "Patreon list and support links": "Liste Patreon et liens de support",
    "player settings": "paramètres utilisateur",
    "Grandfather clock mode": "Mode horloge grand-père",
    "Use game rain sound": "Bruit de pluie du jeu",
    "Use no-thunder rain sound": "Bruit de pluie sans tonnerre",
    "language": "langue",
    "clear local files and settings": "effacer les fichiers locaux et les options",
    "patreon supporters": "supporteurs patreon",
    "Opens developer's Patreon page": "Ouvrir la page Patreon du développeur",
    "(support me!)": "(supportez-moi!)",
    "gold supporters": "supporteurs en or",
    "silver supporters": "supporteurs en argent",
    "bronze supporters": "supporteurs en bronze",
    "patreon": "patreon",
    "(plays once, no loop)": "(joue une fois, pas de répétition)",
    "Are you sure?": "Êtes-vous certain.e?",
    "Click \"OK\" to proceed and delete all local music files and user settings.": "Cliquez sur \"OK\" pour procéder et supprimer les fichiers locaux ainsi que les paramètres utilisateur.",
    "customize": "personnaliser",
    "Enable town tune": "Activer l'hymne",
    "tune settings": "paramètres de l'hymne",
    "offline": "hors-ligne",
    "{{offlineFiles}}/{{totalFiles}} offline hourly music files downloaded": "{{offlineFiles}}/{{totalFiles}} des thèmes horaires hors-ligne téléchargé(s)",
    "{{offlineKKFiles}}/{{totalKKFiles}} offline k.k. music files downloaded": "{{offlineKKFiles}}/{{totalKKFiles}} des chansons de Kéké hors-ligne téléchargé(s)",
    "download all hourly music": "télécharger les thèmes horaires",
    "download all k.k. music": "télécharger les chansons de Kéké",
    "save": "sauvegarder",
    "play": "jouer",
    "failedToLoadSound": "le chargement des thèmes horaires a échoué.",
    "failedToLoadRainSound": "le chargement du son de pluie a échoué.",
    "Play": "Jouer",
    "Pause": "Pause",
    "failedToDownload": "le téléchargement de la musique a échoué.",
    "AC: Population Growing (GC) [Snowy]": "AC: Population Growing (GC) [Neige]",
    "AC: Population Growing (GC) [Sakura]": "AC: Population Growing (GC) [Sakura]",
    "AC: New Horizons (Switch) [Rainy]": "AC: New Horizons (Switch) [Pluie]",
    "AC: New Horizons (Switch) [Snowy]": "AC: New Horizons (Switch) [Neige]",
    "AC: Pocket Camp (Mobile)": "AC: Pocket Camp (Mobile)",
    "Play K.K. music on Saturday nights": "Jouer la musique de Kéké le samedi soir",
    "customize k.k. playlist": "personnaliser la liste de lecture de Kéké",
    "customize town tune": "personnaliser l'hymne",
    "k.k. playlist": "liste de lecture de Kéké",
    "check all": "tout cocher",
    "uncheck all": "tout décocher",
    "radio only": "radio seulement",
    "live only": "acoustique seulement",
    "downloading...": "téléchargement...",
    "Don't download music": "Ne pas télécharger la musique",
    "(saves space, but no offline)": "(économise de l'espace, mais pas de mode hors-ligne)",
    "tip: you can use the mouse wheel to adjust notes!": "astuce: vous pouvez utiliser la molette de souris pour ajuster les notes!",
    "Nook GitHub": "Nook GitHub"
}

**Comment by ardi-techguy** [comment]
I've arranged the code to add in the french translation and am ready for a pull request. I just lack the access to the project.
