### ISSUE TITLE
Songs cannot be played offline despite all songs being pre-downloaded

### ISSUE THREAD

**Issue by OpenSauce04** [mn6/nook-desktop#22]
![image](https://user-images.githubusercontent.com/48618519/215328559-fa47cc19-739d-4183-8dbc-2fc2959a66b3.png)
![image](https://user-images.githubusercontent.com/48618519/215328580-2106583f-1b2d-46e4-b681-f81e467b8c5f.png)

**Comment by mn6** [comment]
Fixed in #27
