### ISSUE TITLE
Using the app on Mac, seems to randomly time out music after a couple of minutes

### ISSUE THREAD

**Issue by martisnotonfire** [mn6/nook-desktop#24]

**Comment by nhihin** [comment]
I had this same issue too on Mac, but only if Grandfather Clock Mode was enabled. Turning off this mode immediately fixed the issue for me.

**Comment by mn6** [comment]
This sounds like Grandfather Clock mode, which is expected behavior. Will close for now unless it isn't Grandfather Clock mode.
