### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by niels-beier** [mn6/nook-desktop#3]
Since in #1 translations were mentioned I thought about a german translation since I'm german my self. Could help with the translation if necessary. This could be also added to #1 since its topic is similar/same.

**Comment by niels-beier** [comment]
Finished for now. I didn't know what Grandfather mode actually does and whether it's implemented in the actual game, so I just translated it.

**Comment by mn6** [comment]
Thanks so much! Added your translations in, https://github.com/mn6/nook-desktop/pull/8
