### ISSUE TITLE
AC: New Leaf (3DS) 9am doesn't wait/rest for the full duration at the end of the loop/gets cut off too soon.

### ISSUE THREAD

**Issue by Andy608** [mn6/nook-desktop#38]
When listening to the 9am New Leaf Soundtrack, (I have only tested the regular soundtrack, not the rain or snow version), the loop does not wait for the full rest duration, but instead loops too quickly and produces a noticeable hitch/loop cut in the soundtrack. Seems like the track is clipped too soon and just needs to be extended a bit.

**Comment by mn6** [comment]
Listened and I think the clip should happen sooner at the end - the song is a little funky so could just be how it's meant to be played, patched it up and uploaded so should be good now
