### ISSUE TITLE
[Suggestion] Normal mode but with Grandfather clock chimes

### ISSUE THREAD

**Issue by sammypanda** [mn6/nook-desktop#76]
I really like the grandfather clock mode for the 🎶 "ding dong" 🎶 (especially when doing stuff for a long time) but i also want the music/rain to keep going/loop.

Maybe the Grandfather clock mode can have a submenu with enabling or disabling playing once/no looping!

**Comment by ROMthesheep** [comment]
What OS are you using and what version? 1.0.1 in windows already shows that behaviour

**Comment by sammypanda** [comment]
> What OS are you using and what version? 1.0.1 in windows already shows that behaviour

This was on Linux: Ubuntu/Pop! OS

I don't remember what version it was on. I will retry soon (on my current system Linux: NixOS).

**Comment by sammypanda** [comment]
It works for me now, closing :)
